# see https://github.com/notFloran/mjml-bundle#binary
mjml:
    renderer: 'binary'
    options:
        binary: '%kernel.project_dir%/node_modules/.bin/mjml'
        service_id: 'App\Service\MjmlRendererService'
        validation_level: skip
