twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        region_service: '@App\Service\Shop\RegionService'
        ad_service: '@App\Service\AdService'
