name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    # ----- Configuration environnement -----
    - name: Téléchargement des sources
      uses: actions/checkout@v2

    - name: Configuration de PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
      env:
        update: true

    # ----- Composer -----
    - name: Validation composer
      run: composer validate

    - name: Récupération du cache composer
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Mise en cache des dépendances composer
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Installation composer
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    # ----- Symfony -----
    # TODO mise en place BD
    - name: Lancement des TU
      run: ./bin/phpunit

    - name: Fix chemin couverture de code
      working-directory: ./var/test/
      run: |
        sed -i 's/\/home\/runner\/work\/vinproject\/vinproject\//\/github\/workspace\//g' phpunit.coverage.xml
        sed -i 's/\/home\/runner\/work\/vinproject\/vinproject\//\/github\/workspace\//g' phpunit.report.xml

    # ----- Sonar -----
    - name: Analyse sonar
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # ----- CodeCov -----
    - name: Couverture de code
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: var/test/phpunit.coverage.xml
